# Generated by Django 5.2.6 on 2025-10-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_complaint_picture_complaint_video_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
