# Generated by Django 5.2.6 on 2025-10-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_profile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Worker', 'Worker'), ('Admin', 'Admin'), ('Superuser', 'Superuser')], default='Citizen', max_length=20),
        ),
    ]
