# Generated by Django 5.2.6 on 2025-10-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
