# Generated by Django 5.2.6 on 2025-10-18 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0007_alter_complaint_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='interested_workers',
            field=models.ManyToManyField(blank=True, related_name='interested_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
