# Generated by Django 5.2.6 on 2025-10-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0009_complaint_assigned_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='worker_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='worker_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
