# Generated by Django 5.2.6 on 2025-10-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0010_complaint_worker_lat_complaint_worker_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
